#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : libebur128
Version  : 1.2.5
Release  : 1
URL      : https://github.com/jiixyj/libebur128/archive/v1.2.5.tar.gz
Source0  : https://github.com/jiixyj/libebur128/archive/v1.2.5.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
Requires: libebur128-lib = %{version}-%{release}
Requires: libebur128-license = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : pkg-config

%description
libebur128
==========
libebur128 is a library that implements the EBU R 128 standard for loudness
normalisation.

%package dev
Summary: dev components for the libebur128 package.
Group: Development
Requires: libebur128-lib = %{version}-%{release}
Provides: libebur128-devel = %{version}-%{release}
Requires: libebur128 = %{version}-%{release}

%description dev
dev components for the libebur128 package.


%package lib
Summary: lib components for the libebur128 package.
Group: Libraries
Requires: libebur128-license = %{version}-%{release}

%description lib
lib components for the libebur128 package.


%package license
Summary: license components for the libebur128 package.
Group: Default

%description license
license components for the libebur128 package.


%prep
%setup -q -n libebur128-1.2.5
cd %{_builddir}/libebur128-1.2.5

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1612373984
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%cmake ..
make  %{?_smp_mflags}
popd

%install
export SOURCE_DATE_EPOCH=1612373984
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/libebur128
cp %{_builddir}/libebur128-1.2.5/COPYING %{buildroot}/usr/share/package-licenses/libebur128/2627ff03833f74ed51a7f43c55d30b249b6a0707
pushd clr-build
%make_install
popd

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/ebur128.h
/usr/lib64/libebur128.so
/usr/lib64/pkgconfig/libebur128.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libebur128.so.1
/usr/lib64/libebur128.so.1.2.5

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/libebur128/2627ff03833f74ed51a7f43c55d30b249b6a0707
